"""End-to-end binder generation with pre-converted .eqx weights."""

import sys

import time
import gemmi
import numpy as np
import jax
import jax.numpy as jnp
import equinox as eqx
from jproteina_complexa.pdb import load_target

from jproteina_complexa.serialization import load_model
from jproteina_complexa.flow_matching import generate, PRODUCTION_SAMPLING, get_schedule
from jproteina_complexa.types import DecoderBatch, TargetCond
from jproteina_complexa.constants import RESTYPE_ATOM37_MASK

print("=" * 70)
print("Binder generation test")
print("=" * 70)

# ---- Load target protein ----
print("\nLoading target (crambin, PDB 1CRN)...")
_chain = gemmi.read_structure("/tmp/pdb/pdb1crn.ent")[0][0]
target_a37, target_a37_mask, target_seq_idx, N_target = load_target(_chain)

AA_CODES = "ACDEFGHIKLMNPQRSTVWY"
AA_3TO1 = {'ALA':'A','CYS':'C','ASP':'D','GLU':'E','PHE':'F','GLY':'G','HIS':'H',
           'ILE':'I','LYS':'K','LEU':'L','MET':'M','ASN':'N','PRO':'P','GLN':'Q',
           'ARG':'R','SER':'S','THR':'T','TRP':'W','TYR':'Y','VAL':'V'}
AA_3LETTER = {v: k for k, v in AA_3TO1.items()}

target_nm = target_a37 / 10.0
print(f"  {N_target} residues (centered)")

# ---- Load models ----
print("\nLoading models from .eqx files...")
t0 = time.perf_counter()
denoiser = load_model("weights/denoiser")
decoder = load_model("weights/decoder")
print(f"  Loaded in {time.perf_counter() - t0:.1f}s")

# ---- Generate ----
N_binder = 50
N_STEPS = 200
LATENT_DIM = 8
B = 1
key = jax.random.PRNGKey(42)

mask = jnp.ones((B, N_binder), dtype=jnp.bool_)

target = TargetCond(
    coords=jnp.array(target_nm)[None],
    atom_mask=jnp.array(target_a37_mask)[None],
    seq=jnp.array(target_seq_idx)[None],
    seq_mask=jnp.ones((B, N_target), dtype=jnp.bool_),
    hotspot_mask=jnp.ones((B, N_target), dtype=jnp.bool_),
)

decode = eqx.filter_jit(decoder)

print(f"\nSampling {N_binder}-residue binder to {N_target}-residue target ({N_STEPS} steps)...")
ts_bb = get_schedule("log", N_STEPS, p1=2.0)
ts_lat = get_schedule("power", N_STEPS, p1=2.0)
print(f"  bb_ca:          schedule=log(p=2), gt=1/t, mode=sc(noise=0.1)")
print(f"  local_latents:  schedule=power(p=2), gt=tan, mode=sc(noise=0.1)")
print(f"  Schedule at midpoint: t_bb={float(ts_bb[N_STEPS//2]):.3f}, t_lat={float(ts_lat[N_STEPS//2]):.3f}")

t_gen = time.perf_counter()
x_bb, x_lat = generate(
    model=eqx.filter_jit(denoiser),
    mask=mask,
    n_residues=N_binder,
    latent_dim=LATENT_DIM,
    key=key,
    nsteps=N_STEPS,
    self_cond=True,
    sampling=PRODUCTION_SAMPLING,
    target=target,
)
jax.block_until_ready(x_bb)
gen_time = time.perf_counter() - t_gen
print(f"  Generation: {gen_time:.1f}s ({gen_time/N_STEPS*1000:.0f}ms/step)")

# ---- Decode ----
print("\nDecoding...")
dec_out = decode(DecoderBatch(z_latent=x_lat, ca_coors_nm=x_bb, mask=mask))
jax.block_until_ready(dec_out.coors_nm)

# ---- Analysis ----
print("\n" + "=" * 70)
print("Generated binder analysis")
print("=" * 70)

pred_seq = "".join(AA_CODES[i] for i in np.array(dec_out.aatype[0]))
binder_ca = np.array(x_bb[0]) * 10.0
ca_dists = np.linalg.norm(np.diff(binder_ca, axis=0), axis=1)
rg = np.sqrt(np.mean(np.sum((binder_ca - binder_ca.mean(0)) ** 2, axis=1)))

target_ca_ang = target_nm[:, 1, :] * 10.0
min_dists = np.min(np.linalg.norm(binder_ca[:, None] - target_ca_ang[None], axis=-1), axis=1)
n_contact = (min_dists < 8.0).sum()

pred_coors = np.array(dec_out.coors_nm[0]) * 10.0
n_ca_bond = np.linalg.norm(pred_coors[:, 1] - pred_coors[:, 0], axis=1)
ca_c_bond = np.linalg.norm(pred_coors[:, 2] - pred_coors[:, 1], axis=1)

print(f"\n  Sequence ({N_binder} res): {pred_seq}")
print(f"\n  Backbone geometry:")
print(f"    CA-CA distances: mean={ca_dists.mean():.2f}A, std={ca_dists.std():.2f}A (expected ~3.8A)")
print(f"    Radius of gyration: {rg:.1f}A")
print(f"\n  Binder-target interface:")
print(f"    Residues within 8A of target: {n_contact}/{N_binder}")
print(f"    Closest approach: {min_dists.min():.1f}A")
print(f"\n  All-atom structure:")
print(f"    N-CA bond: mean={n_ca_bond.mean():.2f}A (expected ~1.46A)")
print(f"    CA-C bond: mean={ca_c_bond.mean():.2f}A (expected ~1.52A)")

from collections import Counter
print(f"\n  AA composition: {dict(sorted(Counter(pred_seq).items()))}")

# ---- Save PDB ----
out_path = "binder_complex.pdb"
binder_amask = np.array(dec_out.atom_mask[0]).astype(np.float32)
binder_resnames = [AA_3LETTER.get(aa, "UNK") for aa in pred_seq]
target_resnames = [AA_3LETTER.get(AA_CODES[idx], "UNK") for idx in target_seq_idx]

with open(out_path, "w") as f:
    f.write("REMARK   Generated by jproteina_complexa (JAX/Equinox Proteina-Complexa)\n")
    f.write(f"REMARK   Binder: {N_binder} residues (chain A)\n")
    f.write(f"REMARK   Target: {N_target} residues (chain B, crambin PDB 1CRN)\n")
    f.write(f"REMARK   Sequence: {pred_seq}\n")
    f.write(f"REMARK   Sampling: {N_STEPS} steps, log/power schedules, SDE (sc)\n")
    serial = 1
    for chain_id, resnames, coords, amask in [
        ("A", binder_resnames, pred_coors, binder_amask),
        ("B", target_resnames, target_a37, target_a37_mask),
    ]:
        n_res = len(resnames)
        for i in range(n_res):
            for j in range(37):
                if amask[i, j] < 0.5:
                    continue
                aname = ATOM_NAMES[j]
                x, y, z = coords[i, j]
                elem = aname[0] if aname[0] in "CNOS" else aname.strip()[:2]
                f.write(f"ATOM  {serial:5d} {aname:^4s} {resnames[i]:>3s} {chain_id}{i+1:4d}    "
                        f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {elem:>2s}\n")
                serial += 1
        f.write(f"TER   {serial:5d}      {resnames[-1]:>3s} {chain_id}{n_res:4d}\n")
        serial += 1
    f.write("END\n")

import os
print(f"\n  Saved: {out_path} ({os.path.getsize(out_path) / 1024:.1f} KB)")

print(f"\n{'=' * 70}")
print("Done!")
print(f"{'=' * 70}")
